services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: opex-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - opex-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: opex-backend
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - opex-network

  frontend:
    image:  paulahakeem/opex_3tier_test_frontend
    container_name: opex-frontend
    environment:
      NEXT_PUBLIC_API_URL: http://backend:3000
      NODE_ENV: production
    ports:
      - "3001:3001"
    depends_on:
      - backend
    networks:
      - opex-network

volumes:
  mysql-data:

networks:
  opex-network:
    driver: bridge
