apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: opex-app
type: Opaque
data:
  # Base64 encoded values
  # rootpassword: Ahmed123@
  mysql-root-password: QWhtZWQxMjNADQo=
  # ahmedadmin
  mysql-user: YWhtZWRhZG1pbg==
  # Ahmed123@
  mysql-password: QWhtZWQxMjNA
